// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbuwvruiykqqyurcwxdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidXd2cnVpeWtxcXl1cmN3eGRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MDE4MzIsImV4cCI6MjA2NTE3NzgzMn0.QTT9lBUyzqd8rtoesvBHjLZYonM6HyBID90Kx7-zq0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);